export const classicWands = [
    {label: 'Acacia', src: '../images/classicWand/classic-acacia.png'},
    {label: 'Alder', src: '../images/classicWand/classic-alder.png'},
    {label: 'Apple', src: '../images/classicWand/classic-apple.png'},
    {label: 'Ash', src: '../images/classicWand/classic-ash.png'},
    {label: 'Aspen', src: '../images/classicWand/classic-aspen.png'},
    {label: 'Beech', src: '../images/classicWand/classic-beech.png'},
    {label: 'Black Walnut', src: '../images/classicWand/classic-black-walnut.png'},
    {label: 'Blackthorn', src: '../images/classicWand/classic-blackthorn.png'},
    {label: 'Cedar', src: '../images/classicWand/classic-cedar.png'},
    {label: 'Cherry', src: '../images/classicWand/classic-cherry.png'},
    {label: 'Chestnut', src: '../images/classicWand/classic-chestnut.png'},
    {label: 'Cypress', src: '../images/classicWand/classic-cypress.png'},
    {label: 'Dogwood', src: '../images/classicWand/classic-dogwood.png'},
    {label: 'Ebony', src: '../images/classicWand/classic-ebony.png'},
    {label: 'Elder', src: '../images/classicWand/classic-elder.png'},
    {label: 'Elm', src: '../images/classicWand/classic-elm.png'},
    {label: 'English Oak', src: '../images/classicWand/classic-english-oak.png'},
    {label: 'Fir', src: '../images/classicWand/classic-fir.png'},
    {label: 'Hawthorn', src: '../images/classicWand/classic-hawthorn.png'},
    {label: 'Hazel', src: '../images/classicWand/classic-hazel.png'},
    {label: 'Holly', src: '../images/classicWand/classic-holly.png'},
    {label: 'Hornbeam', src: '../images/classicWand/classic-hornbeam.png'},
    {label: 'Larch', src: '../images/classicWand/classic-larch.png'},
    {label: 'Laurel', src: '../images/classicWand/classic-laurel.png'},
    {label: 'Maple', src: '../images/classicWand/classic-maple.png'},
    {label: 'Pear', src: '../images/classicWand/classic-pear.png'},
    {label: 'Pine', src: '../images/classicWand/classic-pine.png'},
    {label: 'Poplar', src: '../images/classicWand/classic-poplar.png'},
    {label: 'Red Oak', src: '../images/classicWand/classic-red-oak.png'},
    {label: 'Redwood', src: '../images/classicWand/classic-redwood.png'},
    {label: 'Rowan', src: '../images/classicWand/classic-rowan.png'},
    {label: 'Silver Lime', src: '../images/classicWand/classic-silver-lime.png'},
    {label: 'Spruce', src: '../images/classicWand/classic-spruce.png'},
    {label: 'Sycamore', src: '../images/classicWand/classic-sycamore.png'},
    {label: 'Vine', src: '../images/classicWand/classic-vine.png'},
    {label: 'Walnut', src: '../images/classicWand/classic-walnut.png'},
    {label: 'Willow', src: '../images/classicWand/classic-willow.png'},
    {label: 'Yew', src: '../images/classicWand/classic-yew.png'}
];
