export const classicWands = [
    {label: 'Acacia', src: '../images/classicWand/classic-acacia.png', hex:'#83594B'},
    {label: 'Alder', src: '../images/classicWand/classic-alder.png', hex:'#9D4927'},
    {label: 'Apple', src: '../images/classicWand/classic-apple.png', hex:'#A45420'},
    {label: 'Ash', src: '../images/classicWand/classic-ash.png', hex:'#D4A46E'},
    {label: 'Aspen', src: '../images/classicWand/classic-aspen.png', hex:'#AF8453'},
    {label: 'Beech', src: '../images/classicWand/classic-beech.png', hex:'#B76D3C'},
    {label: 'Black Walnut', src: '../images/classicWand/classic-black-walnut.png', hex:'#413C39'},
    {label: 'Blackthorn', src: '../images/classicWand/classic-blackthorn.png', hex:'#25211E'},
    {label: 'Cedar', src: '../images/classicWand/classic-cedar.png', hex:'#763F2B'},
    {label: 'Cherry', src: '../images/classicWand/classic-cherry.png', hex:'#712918'},
    {label: 'Chestnut', src: '../images/classicWand/classic-chestnut.png', hex:'#953F17'},
    {label: 'Cypress', src: '../images/classicWand/classic-cypress.png', hex:'#A65A1D'},
    {label: 'Dogwood', src: '../images/classicWand/classic-dogwood.png', hex:'#885044'},
    {label: 'Ebony', src: '../images/classicWand/classic-ebony.png', hex:'#4E4445'},
    {label: 'Elder', src: '../images/classicWand/classic-elder.png', hex:'#663F34'},
    {label: 'Elm', src: '../images/classicWand/classic-elm.png', hex:'#602F12'},
    {label: 'English Oak', src: '../images/classicWand/classic-english-oak.png', hex:'#804B29'},
    {label: 'Fir', src: '../images/classicWand/classic-fir.png', hex:'#CE894D'},
    {label: 'Hawthorn', src: '../images/classicWand/classic-hawthorn.png', hex:'#9E3D06'},
    {label: 'Hazel', src: '../images/classicWand/classic-hazel.png', hex:'#6D6250'},
    {label: 'Holly', src: '../images/classicWand/classic-holly.png', hex:'#BBB8A5'},
    {label: 'Hornbeam', src: '../images/classicWand/classic-hornbeam.png', hex:'#A57550'},
    {label: 'Larch', src: '../images/classicWand/classic-larch.png', hex:'#D8BBA5'},
    {label: 'Laurel', src: '../images/classicWand/classic-laurel.png', hex:'#B95C1A'},
    {label: 'Maple', src: '../images/classicWand/classic-maple.png', hex:'#B77A45'},
    {label: 'Pear', src: '../images/classicWand/classic-pear.png', hex:'#B65B3E'},
    {label: 'Pine', src: '../images/classicWand/classic-pine.png', hex:'#D09767'},
    {label: 'Poplar', src: '../images/classicWand/classic-poplar.png', hex:'#76592B'},
    {label: 'Red Oak', src: '../images/classicWand/classic-red-oak.png', hex:'#4C1E12'},
    {label: 'Redwood', src: '../images/classicWand/classic-redwood.png', hex:'#D49182'},
    {label: 'Rowan', src: '../images/classicWand/classic-rowan.png', hex:'#BF9E82'},
    {label: 'Silver Lime', src: '../images/classicWand/classic-silver-lime.png', hex:'#654B49'},
    {label: 'Spruce', src: '../images/classicWand/classic-spruce.png', hex:'#B09F90'},
    {label: 'Sycamore', src: '../images/classicWand/classic-sycamore.png', hex:'#6B2E15'},
    {label: 'Vine', src: '../images/classicWand/classic-vine.png', hex:'#964B1D'},
    {label: 'Walnut', src: '../images/classicWand/classic-walnut.png', hex:'#906145'},
    {label: 'Willow', src: '../images/classicWand/classic-willow.png', hex:'#64411F'},
    {label: 'Yew', src: '../images/classicWand/classic-yew.png', hex:'#903D01'}
];
