export const crookedSpiralWands = [
    {label: 'Acacia', src: '../images/crookedSpiralWand/crooked-spiral-acacia.png', hex: '#83594B'},
    {label: 'Alder', src: '../images/crookedSpiralWand/crooked-spiral-alder.png', hex: '#9D4927'},
    {label: 'Apple', src: '../images/crookedSpiralWand/crooked-spiral-apple.png', hex: '#A45420'},
    {label: 'Ash', src: '../images/crookedSpiralWand/crooked-spiral-ash.png', hex: '#D4A46E'},
    {label: 'Aspen', src: '../images/crookedSpiralWand/crooked-spiral-aspen.png', hex: '#AF8453'},
    {label: 'Beech', src: '../images/crookedSpiralWand/crooked-spiral-beech.png', hex: '#B76D3C'},
    {label: 'Black Walnut', src: '../images/crookedSpiralWand/crooked-spiral-black-walnut.png', hex: '#413C39'},
    {label: 'Blackthorn', src: '../images/crookedSpiralWand/crooked-spiral-blackthorn.png', hex: '#25211E'},
    {label: 'Cedar', src: '../images/crookedSpiralWand/crooked-spiral-cedar.png', hex: '#763F2B'},
    {label: 'Cherry', src: '../images/crookedSpiralWand/crooked-spiral-cherry.png', hex: '#712918'},
    {label: 'Chestnut', src: '../images/crookedSpiralWand/crooked-spiral-chestnut.png', hex: '#953F17'},
    {label: 'Cypress', src: '../images/crookedSpiralWand/crooked-spiral-cypress.png', hex: '#A65A1D'},
    {label: 'Dogwood', src: '../images/crookedSpiralWand/crooked-spiral-dogwood.png', hex: '#885044'},
    {label: 'Ebony', src: '../images/crookedSpiralWand/crooked-spiral-ebony.png', hex: '#4E4445'},
    {label: 'Elder', src: '../images/crookedSpiralWand/crooked-spiral-elder.png', hex: '#663F34'},
    {label: 'Elm', src: '../images/crookedSpiralWand/crooked-spiral-elm.png', hex: '#602F12'},
    {label: 'English Oak', src: '../images/crookedSpiralWand/crooked-spiral-english-oak.png', hex: '#804B29'},
    {label: 'Fir', src: '../images/crookedSpiralWand/crooked-spiral-fir.png', hex: '#CE894D'},
    {label: 'Hawthorn', src: '../images/crookedSpiralWand/crooked-spiral-hawthorn.png', hex: '#9E3D06'},
    {label: 'Hazel', src: '../images/crookedSpiralWand/crooked-spiral-hazel.png', hex: '#6D6250'},
    {label: 'Holly', src: '../images/crookedSpiralWand/crooked-spiral-holly.png', hex: '#BBB8A5'},
    {label: 'Hornbeam', src: '../images/crookedSpiralWand/crooked-spiral-hornbeam.png', hex: '#A57550'},
    {label: 'Larch', src: '../images/crookedSpiralWand/crooked-spiral-larch.png', hex: '#D8BBA5'},
    {label: 'Laurel', src: '../images/crookedSpiralWand/crooked-spiral-laurel.png', hex: '#B95C1A'},
    {label: 'Maple', src: '../images/crookedSpiralWand/crooked-spiral-maple.png', hex: '#B77A45'},
    {label: 'Pear', src: '../images/crookedSpiralWand/crooked-spiral-pear.png', hex: '#B65B3E'},
    {label: 'Pine', src: '../images/crookedSpiralWand/crooked-spiral-pine.png', hex: '#D09767'},
    {label: 'Poplar', src: '../images/crookedSpiralWand/crooked-spiral-poplar.png', hex: '#76592B'},
    {label: 'Red Oak', src: '../images/crookedSpiralWand/crooked-spiral-red-oak.png', hex: '#4C1E12'},
    {label: 'Redwood', src: '../images/crookedSpiralWand/crooked-spiral-redwood.png', hex: '#D49182'},
    {label: 'Rowan', src: '../images/crookedSpiralWand/crooked-spiral-rowan.png', hex: '#BF9E82'},
    {label: 'Silver Lime', src: '../images/crookedSpiralWand/crooked-spiral-silver-lime.png', hex: '#654B49'},
    {label: 'Spruce', src: '../images/crookedSpiralWand/crooked-spiral-spruce.png', hex: '#B09F90'},
    {label: 'Sycamore', src: '../images/crookedSpiralWand/crooked-spiral-sycamore.png', hex: '#6B2E15'},
    {label: 'Vine', src: '../images/crookedSpiralWand/crooked-spiral-vine.png', hex: '#964B1D'},
    {label: 'Walnut', src: '../images/crookedSpiralWand/crooked-spiral-walnut.png', hex: '#906145'},
    {label: 'Willow', src: '../images/crookedSpiralWand/crooked-spiral-willow.png', hex: '#64411F'},
    {label: 'Yew', src: '../images/crookedSpiralWand/crooked-spiral-yew.png', hex: '#903D01'}
];
