export const naturalWands = [
    {label: 'Acacia', src: '../images/naturalWand/natural-acacia.png'},
    {label: 'Alder', src: '../images/naturalWand/natural-alder.png'},
    {label: 'Apple', src: '../images/naturalWand/natural-apple.png'},
    {label: 'Ash', src: '../images/naturalWand/natural-ash.png'},
    {label: 'Aspen', src: '../images/naturalWand/natural-aspen.png'},
    {label: 'Beech', src: '../images/naturalWand/natural-beech.png'},
    {label: 'Black Walnut', src: '../images/naturalWand/natural-black-walnut.png'},
    {label: 'Blackthorn', src: '../images/naturalWand/natural-blackthorn.png'},
    {label: 'Cedar', src: '../images/naturalWand/natural-cedar.png'},
    {label: 'Cherry', src: '../images/naturalWand/natural-cherry.png'},
    {label: 'Chestnut', src: '../images/naturalWand/natural-chestnut.png'},
    {label: 'Cypress', src: '../images/naturalWand/natural-cypress.png'},
    {label: 'Dogwood', src: '../images/naturalWand/natural-dogwood.png'},
    {label: 'Ebony', src: '../images/naturalWand/natural-ebony.png'},
    {label: 'Elder', src: '../images/naturalWand/natural-elder.png'},
    {label: 'Elm', src: '../images/naturalWand/natural-elm.png'},
    {label: 'English Oak', src: '../images/naturalWand/natural-english-oak.png'},
    {label: 'Fir', src: '../images/naturalWand/natural-fir.png'},
    {label: 'Hawthorn', src: '../images/naturalWand/natural-hawthorn.png'},
    {label: 'Hazel', src: '../images/naturalWand/natural-hazel.png'},
    {label: 'Holly', src: '../images/naturalWand/natural-holly.png'},
    {label: 'Hornbeam', src: '../images/naturalWand/natural-hornbeam.png'},
    {label: 'Larch', src: '../images/naturalWand/natural-larch.png'},
    {label: 'Laurel', src: '../images/naturalWand/natural-laurel.png'},
    {label: 'Maple', src: '../images/naturalWand/natural-maple.png'},
    {label: 'Pear', src: '../images/naturalWand/natural-pear.png'},
    {label: 'Pine', src: '../images/naturalWand/natural-pine.png'},
    {label: 'Poplar', src: '../images/naturalWand/natural-poplar.png'},
    {label: 'Red Oak', src: '../images/naturalWand/natural-red-oak.png'},
    {label: 'Redwood', src: '../images/naturalWand/natural-redwood.png'},
    {label: 'Rowan', src: '../images/naturalWand/natural-rowan.png'},
    {label: 'Silver Lime', src: '../images/naturalWand/natural-silver-lime.png'},
    {label: 'Spruce', src: '../images/naturalWand/natural-spruce.png'},
    {label: 'Sycamore', src: '../images/naturalWand/natural-sycamore.png'},
    {label: 'Vine', src: '../images/naturalWand/natural-vine.png'},
    {label: 'Walnut', src: '../images/naturalWand/natural-walnut.png'},
    {label: 'Willow', src: '../images/naturalWand/natural-willow.png'},
    {label: 'Yew', src: '../images/naturalWand/natural-yew.png'}

];
