export const naturalWands = [
    {label: 'Acacia', src: '../images/naturalWand/natural-acacia.png', hex: '#83594B'},
    {label: 'Alder', src: '../images/naturalWand/natural-alder.png', hex: '#9D4927'},
    {label: 'Apple', src: '../images/naturalWand/natural-apple.png', hex: '#A45420'},
    {label: 'Ash', src: '../images/naturalWand/natural-ash.png', hex: '#D4A46E'},
    {label: 'Aspen', src: '../images/naturalWand/natural-aspen.png', hex: '#AF8453'},
    {label: 'Beech', src: '../images/naturalWand/natural-beech.png', hex: '#B76D3C'},
    {label: 'Black Walnut', src: '../images/naturalWand/natural-black-walnut.png', hex: '#413C39'},
    {label: 'Blackthorn', src: '../images/naturalWand/natural-blackthorn.png', hex: '#25211E'},
    {label: 'Cedar', src: '../images/naturalWand/natural-cedar.png', hex: '#763F2B'},
    {label: 'Cherry', src: '../images/naturalWand/natural-cherry.png', hex: '#712918'},
    {label: 'Chestnut', src: '../images/naturalWand/natural-chestnut.png', hex: '#953F17'},
    {label: 'Cypress', src: '../images/naturalWand/natural-cypress.png', hex: '#A65A1D'},
    {label: 'Dogwood', src: '../images/naturalWand/natural-dogwood.png', hex: '#885044'},
    {label: 'Ebony', src: '../images/naturalWand/natural-ebony.png', hex: '#4E4445'},
    {label: 'Elder', src: '../images/naturalWand/natural-elder.png', hex: '#663F34'},
    {label: 'Elm', src: '../images/naturalWand/natural-elm.png', hex: '#602F12'},
    {label: 'English Oak', src: '../images/naturalWand/natural-english-oak.png', hex: '#804B29'},
    {label: 'Fir', src: '../images/naturalWand/natural-fir.png', hex: '#CE894D'},
    {label: 'Hawthorn', src: '../images/naturalWand/natural-hawthorn.png', hex: '#9E3D06'},
    {label: 'Hazel', src: '../images/naturalWand/natural-hazel.png', hex: '#6D6250'},
    {label: 'Holly', src: '../images/naturalWand/natural-holly.png', hex: '#BBB8A5'},
    {label: 'Hornbeam', src: '../images/naturalWand/natural-hornbeam.png', hex: '#A57550'},
    {label: 'Larch', src: '../images/naturalWand/natural-larch.png', hex: '#D8BBA5'},
    {label: 'Laurel', src: '../images/naturalWand/natural-laurel.png', hex: '#B95C1A'},
    {label: 'Maple', src: '../images/naturalWand/natural-maple.png', hex: '#B77A45'},
    {label: 'Pear', src: '../images/naturalWand/natural-pear.png', hex: '#B65B3E'},
    {label: 'Pine', src: '../images/naturalWand/natural-pine.png', hex: '#D09767'},
    {label: 'Poplar', src: '../images/naturalWand/natural-poplar.png', hex: '#76592B'},
    {label: 'Red Oak', src: '../images/naturalWand/natural-red-oak.png', hex: '#4C1E12'},
    {label: 'Redwood', src: '../images/naturalWand/natural-redwood.png', hex: '#D49182'},
    {label: 'Rowan', src: '../images/naturalWand/natural-rowan.png', hex: '#BF9E82'},
    {label: 'Silver Lime', src: '../images/naturalWand/natural-silver-lime.png', hex: '#654B49'},
    {label: 'Spruce', src: '../images/naturalWand/natural-spruce.png', hex: '#B09F90'},
    {label: 'Sycamore', src: '../images/naturalWand/natural-sycamore.png', hex: '#6B2E15'},
    {label: 'Vine', src: '../images/naturalWand/natural-vine.png', hex: '#964B1D'},
    {label: 'Walnut', src: '../images/naturalWand/natural-walnut.png', hex: '#906145'},
    {label: 'Willow', src: '../images/naturalWand/natural-willow.png', hex: '#64411F'},
    {label: 'Yew', src: '../images/naturalWand/natural-yew.png', hex: '#903D01'}

];
