export const notchedWands = [
    {label: 'Acacia', src: '../images/notchedWand/notched-acacia.png', hex:'#83594B'},
    {label: 'Alder', src: '../images/notchedWand/notched-alder.png', hex:'#9D4927'},
    {label: 'Apple', src: '../images/notchedWand/notched-apple.png', hex:'#A45420'},
    {label: 'Ash', src: '../images/notchedWand/notched-ash.png', hex:'#D4A46E'},
    {label: 'Aspen', src: '../images/notchedWand/notched-aspen.png', hex:'#AF8453'},
    {label: 'Beech', src: '../images/notchedWand/notched-beech.png', hex:'#B76D3C'},
    {label: 'Black Walnut', src: '../images/notchedWand/notched-black-walnut.png', hex:'#413C39'},
    {label: 'Blackthorn', src: '../images/notchedWand/notched-blackthorn.png', hex:'#25211E'},
    {label: 'Cedar', src: '../images/notchedWand/notched-cedar.png', hex:'#763F2B'},
    {label: 'Cherry', src: '../images/notchedWand/notched-cherry.png', hex:'#712918'},
    {label: 'Chestnut', src: '../images/notchedWand/notched-chestnut.png', hex:'#953F17'},
    {label: 'Cypress', src: '../images/notchedWand/notched-cypress.png', hex:'#A65A1D'},
    {label: 'Dogwood', src: '../images/notchedWand/notched-dogwood.png', hex:'#885044'},
    {label: 'Ebony', src: '../images/notchedWand/notched-ebony.png', hex:'#4E4445'},
    {label: 'Elder', src: '../images/notchedWand/notched-elder.png', hex:'#663F34'},
    {label: 'Elm', src: '../images/notchedWand/notched-elm.png', hex:'#602F12'},
    {label: 'English Oak', src: '../images/notchedWand/notched-english-oak.png', hex:'#804B29'},
    {label: 'Fir', src: '../images/notchedWand/notched-fir.png', hex:'#CE894D'},
    {label: 'Hawthorn', src: '../images/notchedWand/notched-hawthorn.png', hex:'#9E3D06'},
    {label: 'Hazel', src: '../images/notchedWand/notched-hazel.png', hex:'#6D6250'},
    {label: 'Holly', src: '../images/notchedWand/notched-holly.png', hex:'#BBB8A5'},
    {label: 'Hornbeam', src: '../images/notchedWand/notched-hornbeam.png', hex:'#A57550'},
    {label: 'Larch', src: '../images/notchedWand/notched-larch.png', hex:'#D8BBA5'},
    {label: 'Laurel', src: '../images/notchedWand/notched-laurel.png', hex:'#B95C1A'},
    {label: 'Maple', src: '../images/notchedWand/notched-maple.png', hex:'#B77A45'},
    {label: 'Pear', src: '../images/notchedWand/notched-pear.png', hex:'#B65B3E'},
    {label: 'Pine', src: '../images/notchedWand/notched-pine.png', hex:'#D09767'},
    {label: 'Poplar', src: '../images/notchedWand/notched-poplar.png', hex:'#76592B'},
    {label: 'Red Oak', src: '../images/notchedWand/notched-red-oak.png', hex:'#4C1E12'},
    {label: 'Redwood', src: '../images/notchedWand/notched-redwood.png', hex:'#D49182'},
    {label: 'Rowan', src: '../images/notchedWand/notched-rowan.png', hex:'#BF9E82'},
    {label: 'Silver Lime', src: '../images/notchedWand/notched-silver-lime.png', hex:'#654B49'},
    {label: 'Spruce', src: '../images/notchedWand/notched-spruce.png', hex:'#B09F90'},
    {label: 'Sycamore', src: '../images/notchedWand/notched-sycamore.png', hex:'#6B2E15'},
    {label: 'Vine', src: '../images/notchedWand/notched-vine.png', hex:'#964B1D'},
    {label: 'Walnut', src: '../images/notchedWand/notched-walnut.png', hex:'#906145'},
    {label: 'Willow', src: '../images/notchedWand/notched-willow.png', hex:'#64411F'},
    {label: 'Yew', src: '../images/notchedWand/notched-yew.png', hex:'#903D01'}
];
