export const notchedWands = [
    {label: 'Acacia', src: '../images/notchedWand/notched-acacia.png'},
    {label: 'Alder', src: '../images/notchedWand/notched-alder.png'},
    {label: 'Apple', src: '../images/notchedWand/notched-apple.png'},
    {label: 'Ash', src: '../images/notchedWand/notched-ash.png'},
    {label: 'Aspen', src: '../images/notchedWand/notched-aspen.png'},
    {label: 'Beech', src: '../images/notchedWand/notched-beech.png'},
    {label: 'Black Walnut', src: '../images/notchedWand/notched-black-walnut.png'},
    {label: 'Blackthorn', src: '../images/notchedWand/notched-blackthorn.png'},
    {label: 'Cedar', src: '../images/notchedWand/notched-cedar.png'},
    {label: 'Cherry', src: '../images/notchedWand/notched-cherry.png'},
    {label: 'Chestnut', src: '../images/notchedWand/notched-chestnut.png'},
    {label: 'Cypress', src: '../images/notchedWand/notched-cypress.png'},
    {label: 'Dogwood', src: '../images/notchedWand/notched-dogwood.png'},
    {label: 'Ebony', src: '../images/notchedWand/notched-ebony.png'},
    {label: 'Elder', src: '../images/notchedWand/notched-elder.png'},
    {label: 'Elm', src: '../images/notchedWand/notched-elm.png'},
    {label: 'English Oak', src: '../images/notchedWand/notched-english-oak.png'},
    {label: 'Fir', src: '../images/notchedWand/notched-fir.png'},
    {label: 'Hawthorn', src: '../images/notchedWand/notched-hawthorn.png'},
    {label: 'Hazel', src: '../images/notchedWand/notched-hazel.png'},
    {label: 'Holly', src: '../images/notchedWand/notched-holly.png'},
    {label: 'Hornbeam', src: '../images/notchedWand/notched-hornbeam.png'},
    {label: 'Larch', src: '../images/notchedWand/notched-larch.png'},
    {label: 'Laurel', src: '../images/notchedWand/notched-laurel.png'},
    {label: 'Maple', src: '../images/notchedWand/notched-maple.png'},
    {label: 'Pear', src: '../images/notchedWand/notched-pear.png'},
    {label: 'Pine', src: '../images/notchedWand/notched-pine.png'},
    {label: 'Poplar', src: '../images/notchedWand/notched-poplar.png'},
    {label: 'Red Oak', src: '../images/notchedWand/notched-red-oak.png'},
    {label: 'Redwood', src: '../images/notchedWand/notched-redwood.png'},
    {label: 'Rowan', src: '../images/notchedWand/notched-rowan.png'},
    {label: 'Silver Lime', src: '../images/notchedWand/notched-silver-lime.png'},
    {label: 'Spruce', src: '../images/notchedWand/notched-spruce.png'},
    {label: 'Sycamore', src: '../images/notchedWand/notched-sycamore.png'},
    {label: 'Vine', src: '../images/notchedWand/notched-vine.png'},
    {label: 'Walnut', src: '../images/notchedWand/notched-walnut.png'},
    {label: 'Willow', src: '../images/notchedWand/notched-willow.png'},
    {label: 'Yew', src: '../images/notchedWand/notched-yew.png'}
];
