export const ringedWands = [
    {label: 'Acacia', src: '../images/ringedWand/ringed-acacia.png', hex:'#83594B'},
    {label: 'Alder', src: '../images/ringedWand/ringed-alder.png', hex:'#9D4927'},
    {label: 'Apple', src: '../images/ringedWand/ringed-apple.png', hex:'#A45420'},
    {label: 'Ash', src: '../images/ringedWand/ringed-ash.png', hex:'#D4A46E'},
    {label: 'Aspen', src: '../images/ringedWand/ringed-aspen.png', hex:'#AF8453'},
    {label: 'Beech', src: '../images/ringedWand/ringed-beech.png', hex:'#B76D3C'},
    {label: 'Black Walnut', src: '../images/ringedWand/ringed-black-walnut.png', hex:'#413C39'},
    {label: 'Blackthorn', src: '../images/ringedWand/ringed-blackthorn.png', hex:'#25211E'},
    {label: 'Cedar', src: '../images/ringedWand/ringed-cedar.png', hex:'#763F2B'},
    {label: 'Cherry', src: '../images/ringedWand/ringed-cherry.png', hex:'#712918'},
    {label: 'Chestnut', src: '../images/ringedWand/ringed-chestnut.png', hex:'#953F17'},
    {label: 'Cypress', src: '../images/ringedWand/ringed-cypress.png', hex:'#A65A1D'},
    {label: 'Dogwood', src: '../images/ringedWand/ringed-dogwood.png', hex:'#885044'},
    {label: 'Ebony', src: '../images/ringedWand/ringed-ebony.png', hex:'#4E4445'},
    {label: 'Elder', src: '../images/ringedWand/ringed-elder.png', hex:'#663F34'},
    {label: 'Elm', src: '../images/ringedWand/ringed-elm.png', hex:'#602F12'},
    {label: 'English Oak', src: '../images/ringedWand/ringed-english-oak.png', hex:'#804B29'},
    {label: 'Fir', src: '../images/ringedWand/ringed-fir.png', hex:'#CE894D'},
    {label: 'Hawthorn', src: '../images/ringedWand/ringed-hawthorn.png', hex:'#9E3D06'},
    {label: 'Hazel', src: '../images/ringedWand/ringed-hazel.png', hex:'#6D6250'},
    {label: 'Holly', src: '../images/ringedWand/ringed-holly.png', hex:'#BBB8A5'},
    {label: 'Hornbeam', src: '../images/ringedWand/ringed-hornbeam.png', hex:'#A57550'},
    {label: 'Larch', src: '../images/ringedWand/ringed-larch.png', hex:'#D8BBA5'},
    {label: 'Laurel', src: '../images/ringedWand/ringed-laurel.png', hex:'#B95C1A'},
    {label: 'Maple', src: '../images/ringedWand/ringed-maple.png', hex:'#B77A45'},
    {label: 'Pear', src: '../images/ringedWand/ringed-pear.png', hex:'#B65B3E'},
    {label: 'Pine', src: '../images/ringedWand/ringed-pine.png', hex:'#D09767'},
    {label: 'Poplar', src: '../images/ringedWand/ringed-poplar.png', hex:'#76592B'},
    {label: 'Red Oak', src: '../images/ringedWand/ringed-red-oak.png', hex:'#4C1E12'},
    {label: 'Redwood', src: '../images/ringedWand/ringed-redwood.png', hex:'#D49182'},
    {label: 'Rowan', src: '../images/ringedWand/ringed-rowan.png', hex:'#BF9E82'},
    {label: 'Silver Lime', src: '../images/ringedWand/ringed-silver-lime.png', hex:'#654B49'},
    {label: 'Spruce', src: '../images/ringedWand/ringed-spruce.png', hex:'#B09F90'},
    {label: 'Sycamore', src: '../images/ringedWand/ringed-sycamore.png', hex:'#6B2E15'},
    {label: 'Vine', src: '../images/ringedWand/ringed-vine.png', hex:'#964B1D'},
    {label: 'Walnut', src: '../images/ringedWand/ringed-walnut.png', hex:'#906145'},
    {label: 'Willow', src: '../images/ringedWand/ringed-willow.png', hex:'#64411F'},
    {label: 'Yew', src: '../images/ringedWand/ringed-yew.png', hex:'#903D01'}

];
