export const ringedWands = [
    {label: 'Acacia', src: '../images/ringedWand/ringed-acacia.png'},
    {label: 'Alder', src: '../images/ringedWand/ringed-alder.png'},
    {label: 'Apple', src: '../images/ringedWand/ringed-apple.png'},
    {label: 'Ash', src: '../images/ringedWand/ringed-ash.png'},
    {label: 'Aspen', src: '../images/ringedWand/ringed-aspen.png'},
    {label: 'Beech', src: '../images/ringedWand/ringed-beech.png'},
    {label: 'Black Walnut', src: '../images/ringedWand/ringed-black-walnut.png'},
    {label: 'Blackthorn', src: '../images/ringedWand/ringed-blackthorn.png'},
    {label: 'Cedar', src: '../images/ringedWand/ringed-cedar.png'},
    {label: 'Cherry', src: '../images/ringedWand/ringed-cherry.png'},
    {label: 'Chestnut', src: '../images/ringedWand/ringed-chestnut.png'},
    {label: 'Cypress', src: '../images/ringedWand/ringed-cypress.png'},
    {label: 'Dogwood', src: '../images/ringedWand/ringed-dogwood.png'},
    {label: 'Ebony', src: '../images/ringedWand/ringed-ebony.png'},
    {label: 'Elder', src: '../images/ringedWand/ringed-elder.png'},
    {label: 'Elm', src: '../images/ringedWand/ringed-elm.png'},
    {label: 'English Oak', src: '../images/ringedWand/ringed-english-oak.png'},
    {label: 'Fir', src: '../images/ringedWand/ringed-fir.png'},
    {label: 'Hawthorn', src: '../images/ringedWand/ringed-hawthorn.png'},
    {label: 'Hazel', src: '../images/ringedWand/ringed-hazel.png'},
    {label: 'Holly', src: '../images/ringedWand/ringed-holly.png'},
    {label: 'Hornbeam', src: '../images/ringedWand/ringed-hornbeam.png'},
    {label: 'Larch', src: '../images/ringedWand/ringed-larch.png'},
    {label: 'Laurel', src: '../images/ringedWand/ringed-laurel.png'},
    {label: 'Maple', src: '../images/ringedWand/ringed-maple.png'},
    {label: 'Pear', src: '../images/ringedWand/ringed-pear.png'},
    {label: 'Pine', src: '../images/ringedWand/ringed-pine.png'},
    {label: 'Poplar', src: '../images/ringedWand/ringed-poplar.png'},
    {label: 'Red Oak', src: '../images/ringedWand/ringed-red-oak.png'},
    {label: 'Redwood', src: '../images/ringedWand/ringed-redwood.png'},
    {label: 'Rowan', src: '../images/ringedWand/ringed-rowan.png'},
    {label: 'Silver Lime', src: '../images/ringedWand/ringed-silver-lime.png'},
    {label: 'Spruce', src: '../images/ringedWand/ringed-spruce.png'},
    {label: 'Sycamore', src: '../images/ringedWand/ringed-sycamore.png'},
    {label: 'Vine', src: '../images/ringedWand/ringed-vine.png'},
    {label: 'Walnut', src: '../images/ringedWand/ringed-walnut.png'},
    {label: 'Willow', src: '../images/ringedWand/ringed-willow.png'},
    {label: 'Yew', src: '../images/ringedWand/ringed-yew.png'}

];
