export const SoftSpiralWands = [
    {label: 'Acacia', src: '../images/softSpiralWand/soft-spiral-acacia.png'},
    {label: 'Alder', src: '../images/softSpiralWand/soft-spiral-alder.png'},
    {label: 'Apple', src: '../images/softSpiralWand/soft-spiral-apple.png'},
    {label: 'Ash', src: '../images/softSpiralWand/soft-spiral-ash.png'},
    {label: 'Aspen', src: '../images/softSpiralWand/soft-spiral-aspen.png'},
    {label: 'Beech', src: '../images/softSpiralWand/soft-spiral-beech.png'},
    {label: 'Black Walnut', src: '../images/softSpiralWand/soft-spiral-black-walnut.png'},
    {label: 'Blackthorn', src: '../images/softSpiralWand/soft-spiral-blackthorn.png'},
    {label: 'Cedar', src: '../images/softSpiralWand/soft-spiral-cedar.png'},
    {label: 'Cherry', src: '../images/softSpiralWand/soft-spiral-cherry.png'},
    {label: 'Chestnut', src: '../images/softSpiralWand/soft-spiral-chestnut.png'},
    {label: 'Cypress', src: '../images/softSpiralWand/soft-spiral-cypress.png'},
    {label: 'Dogwood', src: '../images/softSpiralWand/soft-spiral-dogwood.png'},
    {label: 'Ebony', src: '../images/softSpiralWand/soft-spiral-ebony.png'},
    {label: 'Elder', src: '../images/softSpiralWand/soft-spiral-elder.png'},
    {label: 'Elm', src: '../images/softSpiralWand/soft-spiral-elm.png'},
    {label: 'English Oak', src: '../images/softSpiralWand/soft-spiral-english-oak.png'},
    {label: 'Fig', src: '../images/softSpiralWand/soft-spiral-fig.png'},
    {label: 'Hawthorn', src: '../images/softSpiralWand/soft-spiral-hawthorn.png'},
    {label: 'Hazel', src: '../images/softSpiralWand/soft-spiral-hazel.png'},
    {label: 'Holly', src: '../images/softSpiralWand/soft-spiral-holly.png'},
    {label: 'Hornbeam', src: '../images/softSpiralWand/soft-spiral-hornbeam.png'},
    {label: 'Larch', src: '../images/softSpiralWand/soft-spiral-larch.png'},
    {label: 'Laurel', src: '../images/softSpiralWand/soft-spiral-laurel.png'},
    {label: 'Maple', src: '../images/softSpiralWand/soft-spiral-maple.png'},
    {label: 'Pear', src: '../images/softSpiralWand/soft-spiral-pear.png'},
    {label: 'Pine', src: '../images/softSpiralWand/soft-spiral-pine.png'},
    {label: 'Poplar', src: '../images/softSpiralWand/soft-spiral-poplar.png'},
    {label: 'Red Oak', src: '../images/softSpiralWand/soft-spiral-red-oak.png'},
    {label: 'Redwood', src: '../images/softSpiralWand/soft-spiral-redwood.png'},
    {label: 'Rowan', src: '../images/softSpiralWand/soft-spiral-rowan.png'},
    {label: 'Silver Lime', src: '../images/softSpiralWand/soft-spiral-silver-lime.png'},
    {label: 'Spruce', src: '../images/softSpiralWand/soft-spiral-spruce.png'},
    {label: 'Sycamore', src: '../images/softSpiralWand/soft-spiral-sycamore.png'},
    {label: 'Vine', src: '../images/softSpiralWand/soft-spiral-vine.png'},
    {label: 'Walnut', src: '../images/softSpiralWand/soft-spiral-walnut.png'},
    {label: 'Willow', src: '../images/softSpiralWand/soft-spiral-willow.png'},
    {label: 'Yew', src: '../images/softSpiralWand/soft-spiral-yew.png'},
];