export const SpiralWands = [
    {label: 'Acacia', src: '../images/spiralWand/spiral-acacia.png'},
    {label: 'Alder', src: '../images/spiralWand/spiral-alder.png'},
    {label: 'Apple', src: '../images/spiralWand/spiral-apple.png'},
    {label: 'Ash', src: '../images/spiralWand/spiral-ash.png'},
    {label: 'Aspen', src: '../images/spiralWand/spiral-aspen.png'},
    {label: 'Beech', src: '../images/spiralWand/spiral-beech.png'},
    {label: 'Black Walnut', src: '../images/spiralWand/spiral-black-walnut.png'},
    {label: 'Blackthorn', src: '../images/spiralWand/spiral-blackthorn.png'},
    {label: 'Cedar', src: '../images/spiralWand/spiral-cedar.png'},
    {label: 'Cherry', src: '../images/spiralWand/spiral-cherry.png'},
    {label: 'Chestnut', src: '../images/spiralWand/spiral-chestnut.png'},
    {label: 'Cypress', src: '../images/spiralWand/spiral-cypress.png'},
    {label: 'Dogwood', src: '../images/spiralWand/spiral-dogwood.png'},
    {label: 'Ebony', src: '../images/spiralWand/spiral-ebony.png'},
    {label: 'Elder', src: '../images/spiralWand/spiral-elder.png'},
    {label: 'Elm', src: '../images/spiralWand/spiral-elm.png'},
    {label: 'English Oak', src: '../images/spiralWand/spiral-english-oak.png'},
    {label: 'Fig', src: '../images/spiralWand/spiral-fig.png'},
    {label: 'Hawthorn', src: '../images/spiralWand/spiral-hawthorn.png'},
    {label: 'Hazel', src: '../images/spiralWand/spiral-hazel.png'},
    {label: 'Holly', src: '../images/spiralWand/spiral-holly.png'},
    {label: 'Hornbeam', src: '../images/spiralWand/spiral-hornbeam.png'},
    {label: 'Larch', src: '../images/spiralWand/spiral-larch.png'},
    {label: 'Laurel', src: '../images/spiralWand/spiral-laurel.png'},
    {label: 'Maple', src: '../images/spiralWand/spiral-maple.png'},
    {label: 'Pear', src: '../images/spiralWand/spiral-pear.png'},
    {label: 'Pine', src: '../images/spiralWand/spiral-pine.png'},
    {label: 'Poplar', src: '../images/spiralWand/spiral-poplar.png'},
    {label: 'Red Oak', src: '../images/spiralWand/spiral-red-oak.png'},
    {label: 'Redwood', src: '../images/spiralWand/spiral-redwood.png'},
    {label: 'Rowan', src: '../images/spiralWand/spiral-rowan.png'},
    {label: 'Silver Lime', src: '../images/spiralWand/spiral-silver-lime.png'},
    {label: 'Spruce', src: '../images/spiralWand/spiral-spruce.png'},
    {label: 'Sycamore', src: '../images/spiralWand/spiral-sycamore.png'},
    {label: 'Vine', src: '../images/spiralWand/spiral-vine.png'},
    {label: 'Walnut', src: '../images/spiralWand/spiral-walnut.png'},
    {label: 'Willow', src: '../images/spiralWand/spiral-willow.png'},
    {label: 'Yew', src: '../images/spiralWand/spiral-yew.png'},
];