export const spiralWands = [
    {label: 'Acacia', src: '../images/spiralWand/spiral-acacia.png', hex:'#83594B'},
    {label: 'Alder', src: '../images/spiralWand/spiral-alder.png', hex:'#9D4927'},
    {label: 'Apple', src: '../images/spiralWand/spiral-apple.png', hex:'#A45420'},
    {label: 'Ash', src: '../images/spiralWand/spiral-ash.png', hex:'#D4A46E'},
    {label: 'Aspen', src: '../images/spiralWand/spiral-aspen.png', hex:'#AF8453'},
    {label: 'Beech', src: '../images/spiralWand/spiral-beech.png', hex:'#B76D3C'},
    {label: 'Black Walnut', src: '../images/spiralWand/spiral-black-walnut.png', hex:'#413C39'},
    {label: 'Blackthorn', src: '../images/spiralWand/spiral-blackthorn.png', hex:'#25211E'},
    {label: 'Cedar', src: '../images/spiralWand/spiral-cedar.png', hex:'#763F2B'},
    {label: 'Cherry', src: '../images/spiralWand/spiral-cherry.png', hex:'#712918'},
    {label: 'Chestnut', src: '../images/spiralWand/spiral-chestnut.png', hex:'#953F17'},
    {label: 'Cypress', src: '../images/spiralWand/spiral-cypress.png', hex:'#A65A1D'},
    {label: 'Dogwood', src: '../images/spiralWand/spiral-dogwood.png', hex:'#885044'},
    {label: 'Ebony', src: '../images/spiralWand/spiral-ebony.png', hex:'#4E4445'},
    {label: 'Elder', src: '../images/spiralWand/spiral-elder.png', hex:'#663F34'},
    {label: 'Elm', src: '../images/spiralWand/spiral-elm.png', hex:'#602F12'},
    {label: 'English Oak', src: '../images/spiralWand/spiral-english-oak.png', hex:'#804B29'},
    {label: 'Fir', src: '../images/spiralWand/spiral-fir.png', hex:'#CE894D'},
    {label: 'Hawthorn', src: '../images/spiralWand/spiral-hawthorn.png', hex:'#9E3D06'},
    {label: 'Hazel', src: '../images/spiralWand/spiral-hazel.png', hex:'#6D6250'},
    {label: 'Holly', src: '../images/spiralWand/spiral-holly.png', hex:'#BBB8A5'},
    {label: 'Hornbeam', src: '../images/spiralWand/spiral-hornbeam.png', hex:'#A57550'},
    {label: 'Larch', src: '../images/spiralWand/spiral-larch.png', hex:'#D8BBA5'},
    {label: 'Laurel', src: '../images/spiralWand/spiral-laurel.png', hex:'#B95C1A'},
    {label: 'Maple', src: '../images/spiralWand/spiral-maple.png', hex:'#B77A45'},
    {label: 'Pear', src: '../images/spiralWand/spiral-pear.png', hex:'#B65B3E'},
    {label: 'Pine', src: '../images/spiralWand/spiral-pine.png', hex:'#D09767'},
    {label: 'Poplar', src: '../images/spiralWand/spiral-poplar.png', hex:'#76592B'},
    {label: 'Red Oak', src: '../images/spiralWand/spiral-red-oak.png', hex:'#4C1E12'},
    {label: 'Redwood', src: '../images/spiralWand/spiral-redwood.png', hex:'#D49182'},
    {label: 'Rowan', src: '../images/spiralWand/spiral-rowan.png', hex:'#BF9E82'},
    {label: 'Silver Lime', src: '../images/spiralWand/spiral-silver-lime.png', hex:'#654B49'},
    {label: 'Spruce', src: '../images/spiralWand/spiral-spruce.png', hex:'#B09F90'},
    {label: 'Sycamore', src: '../images/spiralWand/spiral-sycamore.png', hex:'#6B2E15'},
    {label: 'Vine', src: '../images/spiralWand/spiral-vine.png', hex:'#964B1D'},
    {label: 'Walnut', src: '../images/spiralWand/spiral-walnut.png', hex:'#906145'},
    {label: 'Willow', src: '../images/spiralWand/spiral-willow.png', hex:'#64411F'},
    {label: 'Yew', src: '../images/spiralWand/spiral-yew.png', hex:'#903D01'}
];
