export const StalkWands = [
    {label: 'Acacia', src: '../images/stalkWand/stalk-acacia.png'},
    {label: 'Alder', src: '../images/stalkWand/stalk-alder.png'},
    {label: 'Apple', src: '../images/stalkWand/stalk-apple.png'},
    {label: 'Ash', src: '../images/stalkWand/stalk-ash.png'},
    {label: 'Aspen', src: '../images/stalkWand/stalk-aspen.png'},
    {label: 'Beech', src: '../images/stalkWand/stalk-beech.png'},
    {label: 'Black Walnut', src: '../images/stalkWand/stalk-black-walnut.png'},
    {label: 'Blackthorn', src: '../images/stalkWand/stalk-blackthorn.png'},
    {label: 'Cedar', src: '../images/stalkWand/stalk-cedar.png'},
    {label: 'Cherry', src: '../images/stalkWand/stalk-cherry.png'},
    {label: 'Chestnut', src: '../images/stalkWand/stalk-chestnut.png'},
    {label: 'Cypress', src: '../images/stalkWand/stalk-cypress.png'},
    {label: 'Dogwood', src: '../images/stalkWand/stalk-dogwood.png'},
    {label: 'Ebony', src: '../images/stalkWand/stalk-ebony.png'},
    {label: 'Elder', src: '../images/stalkWand/stalk-elder.png'},
    {label: 'Elm', src: '../images/stalkWand/stalk-elm.png'},
    {label: 'English Oak', src: '../images/stalkWand/stalk-english-oak.png'},
    {label: 'Fig', src: '../images/stalkWand/stalk-fig.png'},
    {label: 'Hawthorn', src: '../images/stalkWand/stalk-hawthorn.png'},
    {label: 'Hazel', src: '../images/stalkWand/stalk-hazel.png'},
    {label: 'Holly', src: '../images/stalkWand/stalk-holly.png'},
    {label: 'Hornbeam', src: '../images/stalkWand/stalk-hornbeam.png'},
    {label: 'Larch', src: '../images/stalkWand/stalk-larch.png'},
    {label: 'Laurel', src: '../images/stalkWand/stalk-laurel.png'},
    {label: 'Maple', src: '../images/stalkWand/stalk-maple.png'},
    {label: 'Pear', src: '../images/stalkWand/stalk-pear.png'},
    {label: 'Pine', src: '../images/stalkWand/stalk-pine.png'},
    {label: 'Poplar', src: '../images/stalkWand/stalk-poplar.png'},
    {label: 'Red Oak', src: '../images/stalkWand/stalk-red-oak.png'},
    {label: 'Redwood', src: '../images/stalkWand/stalk-redwood.png'},
    {label: 'Rowan', src: '../images/stalkWand/stalk-rowan.png'},
    {label: 'Silver Lime', src: '../images/stalkWand/stalk-silver-lime.png'},
    {label: 'Spruce', src: '../images/stalkWand/stalk-spruce.png'},
    {label: 'Sycamore', src: '../images/stalkWand/stalk-sycamore.png'},
    {label: 'Vine', src: '../images/stalkWand/stalk-vine.png'},
    {label: 'Walnut', src: '../images/stalkWand/stalk-walnut.png'},
    {label: 'Willow', src: '../images/stalkWand/stalk-willow.png'},
    {label: 'Yew', src: '../images/stalkWand/stalk-yew.png'},
];