export const stalkWands = [
    {label: 'Acacia', src: '../images/stalkWand/stalk-acacia.png', hex:'#83594B'},
    {label: 'Alder', src: '../images/stalkWand/stalk-alder.png', hex:'#9D4927'},
    {label: 'Apple', src: '../images/stalkWand/stalk-apple.png', hex:'#A45420'},
    {label: 'Ash', src: '../images/stalkWand/stalk-ash.png', hex:'#D4A46E'},
    {label: 'Aspen', src: '../images/stalkWand/stalk-aspen.png', hex:'#AF8453'},
    {label: 'Beech', src: '../images/stalkWand/stalk-beech.png', hex:'#B76D3C'},
    {label: 'Black Walnut', src: '../images/stalkWand/stalk-black-walnut.png', hex:'#413C39'},
    {label: 'Blackthorn', src: '../images/stalkWand/stalk-blackthorn.png', hex:'#25211E'},
    {label: 'Cedar', src: '../images/stalkWand/stalk-cedar.png', hex:'#763F2B'},
    {label: 'Cherry', src: '../images/stalkWand/stalk-cherry.png', hex:'#712918'},
    {label: 'Chestnut', src: '../images/stalkWand/stalk-chestnut.png', hex:'#953F17'},
    {label: 'Cypress', src: '../images/stalkWand/stalk-cypress.png', hex:'#A65A1D'},
    {label: 'Dogwood', src: '../images/stalkWand/stalk-dogwood.png', hex:'#885044'},
    {label: 'Ebony', src: '../images/stalkWand/stalk-ebony.png', hex:'#4E4445'},
    {label: 'Elder', src: '../images/stalkWand/stalk-elder.png', hex:'#663F34'},
    {label: 'Elm', src: '../images/stalkWand/stalk-elm.png', hex:'#602F12'},
    {label: 'English Oak', src: '../images/stalkWand/stalk-english-oak.png', hex:'#804B29'},
    {label: 'Fir', src: '../images/stalkWand/stalk-fir.png', hex:'#CE894D'},
    {label: 'Hawthorn', src: '../images/stalkWand/stalk-hawthorn.png', hex:'#9E3D06'},
    {label: 'Hazel', src: '../images/stalkWand/stalk-hazel.png', hex:'#6D6250'},
    {label: 'Holly', src: '../images/stalkWand/stalk-holly.png', hex:'#BBB8A5'},
    {label: 'Hornbeam', src: '../images/stalkWand/stalk-hornbeam.png', hex:'#A57550'},
    {label: 'Larch', src: '../images/stalkWand/stalk-larch.png', hex:'#D8BBA5'},
    {label: 'Laurel', src: '../images/stalkWand/stalk-laurel.png', hex:'#B95C1A'},
    {label: 'Maple', src: '../images/stalkWand/stalk-maple.png', hex:'#B77A45'},
    {label: 'Pear', src: '../images/stalkWand/stalk-pear.png', hex:'#B65B3E'},
    {label: 'Pine', src: '../images/stalkWand/stalk-pine.png', hex:'#D09767'},
    {label: 'Poplar', src: '../images/stalkWand/stalk-poplar.png', hex:'#76592B'},
    {label: 'Red Oak', src: '../images/stalkWand/stalk-red-oak.png', hex:'#4C1E12'},
    {label: 'Redwood', src: '../images/stalkWand/stalk-redwood.png', hex:'#D49182'},
    {label: 'Rowan', src: '../images/stalkWand/stalk-rowan.png', hex:'#BF9E82'},
    {label: 'Silver Lime', src: '../images/stalkWand/stalk-silver-lime.png', hex:'#654B49'},
    {label: 'Spruce', src: '../images/stalkWand/stalk-spruce.png', hex:'#B09F90'},
    {label: 'Sycamore', src: '../images/stalkWand/stalk-sycamore.png', hex:'#6B2E15'},
    {label: 'Vine', src: '../images/stalkWand/stalk-vine.png', hex:'#964B1D'},
    {label: 'Walnut', src: '../images/stalkWand/stalk-walnut.png', hex:'#906145'},
    {label: 'Willow', src: '../images/stalkWand/stalk-willow.png', hex:'#64411F'},
    {label: 'Yew', src: '../images/stalkWand/stalk-yew.png', hex:'#903D01'}
];
